name: Check Bazel/Erlang.mk Equivalence on Release Branches
on:
  schedule:
  - cron: '0 2 * * *'
  workflow_dispatch:
jobs:
  check-main:
    uses: ./.github/workflows/check-build-system-equivalence.yaml
    with:
      ref: refs/heads/main
      erlang_version: 26.1
      elixir_version: 1.15
      project_version: 3.13.0

  check-v3_12_x:
    uses: ./.github/workflows/check-build-system-equivalence.yaml
    with:
      ref: refs/heads/v3.12.x
      erlang_version: 26.1
      elixir_version: 1.15
      project_version: 3.12.0

  check-v3_11_x:
    uses: ./.github/workflows/check-build-system-equivalence.yaml
    with:
      ref: refs/heads/v3.11.x
      erlang_version: 26.1
      elixir_version: 1.15
      project_version: 3.11.0
